export const WORLDCUP_2026_COUNTRIES = [
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'Brasil', flag: '🇧🇷' },
  { name: 'Francia', flag: '🇫🇷' },
  { name: 'España', flag: '🇪🇸' },
  { name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name: 'Alemania', flag: '🇩🇪' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Países Bajos', flag: '🇳🇱' },
  { name: 'Uruguay', flag: '🇺🇾' },
  { name: 'México', flag: '🇲🇽' },
  { name: 'Estados Unidos', flag: '🇺🇸' },
  { name: 'Canadá', flag: '🇨🇦' },
  { name: 'Ecuador', flag: '🇪🇨' },
  { name: 'Colombia', flag: '🇨🇴' },
  { name: 'Chile', flag: '🇨🇱' },
  { name: 'Venezuela', flag: '🇻🇪' },
  { name: 'Perú', flag: '🇵🇪' },
  { name: 'Bolivia', flag: '🇧🇴' },
  { name: 'Paraguay', flag: '🇵🇾' },
  { name: 'Italia', flag: '🇮🇹' },
  { name: 'Bélgica', flag: '🇧🇪' },
  { name: 'Croacia', flag: '🇭🇷' },
  { name: 'Suiza', flag: '🇨🇭' },
  { name: 'Turquía', flag: '🇹🇷' },
  { name: 'Polonia', flag: '🇵🇱' },
  { name: 'Serbia', flag: '🇷🇸' },
  { name: 'Ucrania', flag: '🇺🇦' },
  { name: 'Austria', flag: '🇦🇹' },
  { name: 'Escocia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { name: 'Dinamarca', flag: '🇩🇰' },
  { name: 'Suecia', flag: '🇸🇪' },
  { name: 'Noruega', flag: '🇳🇴' },
  { name: 'Marruecos', flag: '🇲🇦' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Egipto', flag: '🇪🇬' },
  { name: 'Costa de Marfil', flag: '🇨🇮' },
  { name: 'Camerún', flag: '🇨🇲' },
  { name: 'Arabia Saudita', flag: '🇸🇦' },
  { name: 'Japón', flag: '🇯🇵' },
  { name: 'Corea del Sur', flag: '🇰🇷' },
  { name: 'Australia', flag: '🇦🇺' },
  { name: 'Irán', flag: '🇮🇷' },
  { name: 'Qatar', flag: '🇶🇦' },
  { name: 'Costa Rica', flag: '🇨🇷' },
  { name: 'Honduras', flag: '🇭🇳' },
  { name: 'Jamaica', flag: '🇯🇲' },
  { name: 'Nueva Zelanda', flag: '🇳🇿' },
] as const;
