/** Lista editable de países del Mundial 2026 (48 selecciones). */
export const WORLDCUP_2026_COUNTRIES = [
  { name: 'Argentina', code: 'ARG', flag: '🇦🇷' },
  { name: 'Brasil', code: 'BRA', flag: '🇧🇷' },
  { name: 'Francia', code: 'FRA', flag: '🇫🇷' },
  { name: 'España', code: 'ESP', flag: '🇪🇸' },
  { name: 'Inglaterra', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { name: 'Alemania', code: 'GER', flag: '🇩🇪' },
  { name: 'Portugal', code: 'POR', flag: '🇵🇹' },
  { name: 'Países Bajos', code: 'NED', flag: '🇳🇱' },
  { name: 'Uruguay', code: 'URU', flag: '🇺🇾' },
  { name: 'México', code: 'MEX', flag: '🇲🇽' },
  { name: 'Estados Unidos', code: 'USA', flag: '🇺🇸' },
  { name: 'Canadá', code: 'CAN', flag: '🇨🇦' },
  { name: 'Ecuador', code: 'ECU', flag: '🇪🇨' },
  { name: 'Colombia', code: 'COL', flag: '🇨🇴' },
  { name: 'Chile', code: 'CHI', flag: '🇨🇱' },
  { name: 'Venezuela', code: 'VEN', flag: '🇻🇪' },
  { name: 'Perú', code: 'PER', flag: '🇵🇪' },
  { name: 'Bolivia', code: 'BOL', flag: '🇧🇴' },
  { name: 'Paraguay', code: 'PAR', flag: '🇵🇾' },
  { name: 'Italia', code: 'ITA', flag: '🇮🇹' },
  { name: 'Bélgica', code: 'BEL', flag: '🇧🇪' },
  { name: 'Croacia', code: 'CRO', flag: '🇭🇷' },
  { name: 'Suiza', code: 'SUI', flag: '🇨🇭' },
  { name: 'Turquía', code: 'TUR', flag: '🇹🇷' },
  { name: 'Polonia', code: 'POL', flag: '🇵🇱' },
  { name: 'Serbia', code: 'SRB', flag: '🇷🇸' },
  { name: 'Ucrania', code: 'UKR', flag: '🇺🇦' },
  { name: 'Austria', code: 'AUT', flag: '🇦🇹' },
  { name: 'Escocia', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { name: 'Dinamarca', code: 'DEN', flag: '🇩🇰' },
  { name: 'Suecia', code: 'SWE', flag: '🇸🇪' },
  { name: 'Noruega', code: 'NOR', flag: '🇳🇴' },
  { name: 'Marruecos', code: 'MAR', flag: '🇲🇦' },
  { name: 'Senegal', code: 'SEN', flag: '🇸🇳' },
  { name: 'Nigeria', code: 'NGA', flag: '🇳🇬' },
  { name: 'Egipto', code: 'EGY', flag: '🇪🇬' },
  { name: 'Costa de Marfil', code: 'CIV', flag: '🇨🇮' },
  { name: 'Camerún', code: 'CMR', flag: '🇨🇲' },
  { name: 'Arabia Saudita', code: 'KSA', flag: '🇸🇦' },
  { name: 'Japón', code: 'JPN', flag: '🇯🇵' },
  { name: 'Corea del Sur', code: 'KOR', flag: '🇰🇷' },
  { name: 'Australia', code: 'AUS', flag: '🇦🇺' },
  { name: 'Irán', code: 'IRN', flag: '🇮🇷' },
  { name: 'Qatar', code: 'QAT', flag: '🇶🇦' },
  { name: 'Costa Rica', code: 'CRC', flag: '🇨🇷' },
  { name: 'Honduras', code: 'HON', flag: '🇭🇳' },
  { name: 'Jamaica', code: 'JAM', flag: '🇯🇲' },
  { name: 'Nueva Zelanda', code: 'NZL', flag: '🇳🇿' },
] as const;
