'use client';
import QRCode from 'qrcode';
import { api } from '@/lib/api';

export async function printFiscalReceipt(receipt:any, existingPopup?: Window | null) {
 const popup=existingPopup || window.open('','_blank','width=420,height=720'); if(!popup){alert('El navegador bloqueó la ventana de impresión.');return;}
 const doc=receipt.fiscalDocument; const qr=doc?.qrPayload?await QRCode.toDataURL(doc.qrPayload,{width:220,margin:1}):'';
 const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
 const rows=receipt.items.map((i:any)=>`<tr><td>${esc(i.qty)} x ${esc(i.name)}</td><td>$${Number(i.subtotal).toFixed(2)}</td></tr>`).join(''); const fiscal=doc?.kind==='FACTURA_C'&&doc?.status==='AUTHORIZED';
 popup.document.write(`<!doctype html><html><head><title>Comprobante</title><style>@page{size:58mm auto;margin:2mm}body{font-family:monospace;width:54mm;margin:0;font-size:11px;color:#000}h1,h2,p{text-align:center;margin:4px 0}.internal{font-size:15px;font-weight:bold;border:2px solid #000;padding:6px}table{width:100%;border-collapse:collapse}td{padding:3px 0;border-bottom:1px dashed #777}td:last-child{text-align:right}.total{font-size:15px;font-weight:bold;text-align:right;margin:8px 0}.qr{display:block;width:36mm;height:36mm;margin:5px auto}.line{border-top:1px dashed #000;margin:6px 0}</style></head><body><h2>${esc(receipt.business.name)}</h2><p>CUIT: ${esc(receipt.business.cuit)}</p><p>${esc(receipt.business.address)}</p><div class="line"></div>${fiscal?`<h1>FACTURA C</h1><p>PV ${String(doc.pointOfSale).padStart(5,'0')} · Nº ${String(doc.receiptNumber).padStart(8,'0')}</p>`:`<p class="internal">COMPROBANTE INTERNO<br>NO VÁLIDO COMO FACTURA</p>`}<p>${new Date(receipt.createdAt).toLocaleString('es-AR')}</p><table>${rows}</table>${Number(receipt.discount)>0?`<p>Descuento: -$${Number(receipt.discount).toFixed(2)}</p>`:''}<p class="total">TOTAL $${Number(receipt.totalFinal).toFixed(2)}</p><p>Pago: ${esc(receipt.paymentMethod)}</p>${fiscal?`<p>CAE: ${esc(doc.cae)}</p><p>Vto. CAE: ${new Date(doc.caeExpiresAt).toLocaleDateString('es-AR')}</p><img class="qr" src="${qr}"/>`:''}<p>Gracias por su compra</p><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`); popup.document.close();
}
export function FiscalReceiptModal({ receipt, onClose, onRefresh }: { receipt:any; onClose:()=>void; onRefresh:(r:any)=>void }) {
 const doc=receipt.fiscalDocument; const retry=async()=>{await api(`/fiscal/sales/${receipt.id}/retry`,{method:'POST'});onRefresh(await api(`/fiscal/sales/${receipt.id}/receipt`));};
 return <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-[70]"><div className="bg-slate-900 border border-slate-700 rounded-xl p-6 max-w-md w-full mx-4"><h2 className="text-xl font-bold text-white mb-2">Venta registrada</h2>{doc?.kind==='INTERNAL'?<div className="rounded-lg border border-slate-600 bg-slate-800 p-4 mb-4"><p className="font-bold text-slate-200">COMPROBANTE INTERNO</p><p className="text-sm text-amber-400">No válido como factura</p></div>:doc?.status==='AUTHORIZED'?<div className="rounded-lg border border-emerald-700 bg-emerald-950/20 p-4 mb-4"><p className="font-bold text-emerald-300">Factura C autorizada</p><p className="text-sm text-slate-300">Nº {String(doc.pointOfSale).padStart(5,'0')}-{String(doc.receiptNumber).padStart(8,'0')} · CAE {doc.cae}</p></div>:<div className="rounded-lg border border-red-700 bg-red-950/20 p-4 mb-4"><p className="font-bold text-red-300">La venta se guardó, pero ARCA no autorizó</p><p className="text-sm text-red-200 mt-1">{doc?.errorMessage}</p><button onClick={()=>void retry()} className="mt-3 px-3 py-2 rounded bg-red-700 text-white text-sm">Reintentar ARCA</button></div>}<p className="text-2xl font-bold text-right text-white mb-4">Total ${Number(receipt.totalFinal).toFixed(2)}</p><div className="grid grid-cols-2 gap-2"><button onClick={()=>void printFiscalReceipt(receipt)} className="py-3 rounded-lg btn-brand font-bold">Imprimir</button><button onClick={onClose} className="py-3 rounded-lg bg-slate-700 text-white font-bold">No imprimir</button></div></div></div>;
}