'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

type FiscalConfig = { enabled: boolean; environment: 'homologation'|'production'; cuit: string; pointOfSale: number; legalName?: string; grossIncomeNumber?: string; activityStartDate?: string; address?: string; hasCertificate: boolean; hasPrivateKey: boolean; certificateExpiresAt?: string };
type FiscalForm = { enabled:boolean; environment:'homologation'|'production'; cuit:string; pointOfSale:number; legalName:string; grossIncomeNumber:string; activityStartDate:string; address:string; certificate:string; privateKey:string };
const empty: FiscalForm = { enabled: false, environment: 'homologation', cuit: '', pointOfSale: 1, legalName: '', grossIncomeNumber: '', activityStartDate: '', address: '', certificate: '', privateKey: '' };
export default function FiscalSettings() {
 const [form,setForm]=useState(empty); const [meta,setMeta]=useState<FiscalConfig|null>(null); const [saving,setSaving]=useState(false); const [testing,setTesting]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{ api<FiscalConfig|null>('/fiscal/config').then(c=>{ if(!c)return; setMeta(c); setForm(f=>({...f,enabled:c.enabled,environment:c.environment,cuit:c.cuit,pointOfSale:c.pointOfSale,legalName:c.legalName||'',grossIncomeNumber:c.grossIncomeNumber||'',activityStartDate:c.activityStartDate?.slice(0,10)||'',address:c.address||''})); }).catch(()=>{}); },[]);
 const readFile=(file:File|undefined,key:'certificate'|'privateKey')=>{ if(!file)return; const reader=new FileReader(); reader.onload=()=>setForm(f=>({...f,[key]:String(reader.result||'')})); reader.readAsText(file); };
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');try{const c=await api<FiscalConfig>('/fiscal/config',{method:'PUT',body:JSON.stringify(form)});setMeta(c);setForm(f=>({...f,certificate:'',privateKey:''}));setMessage('Configuración fiscal guardada.');}catch(e){setMessage(e instanceof Error?e.message:'Error al guardar');}finally{setSaving(false)}};
 const test=async()=>{setTesting(true);setMessage('');try{const r=await api<{message:string;lastAuthorized:number}>('/fiscal/test',{method:'POST'});setMessage(`${r.message} Última Factura C: ${r.lastAuthorized}.`);}catch(e){setMessage(e instanceof Error?e.message:'Falló la prueba');}finally{setTesting(false)}};
 const input='w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-600 text-slate-100';
 return <form onSubmit={save} className="space-y-4 rounded-lg border border-cyan-800/50 bg-cyan-950/15 p-6 mb-6">
  <div className="flex items-center justify-between gap-3"><div><h2 className="font-medium text-cyan-200">Facturación electrónica ARCA</h2><p className="text-xs text-slate-500 mt-1">Configuración propia de este kiosco para emitir Factura C desde el POS.</p></div><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/> Activada</label></div>
  <div className="grid sm:grid-cols-2 gap-3"><div><label className="text-sm text-slate-400">Ambiente</label><select className={input} value={form.environment} onChange={e=>setForm(f=>({...f,environment:e.target.value as any}))}><option value="homologation">Homologación (pruebas)</option><option value="production">Producción (facturas reales)</option></select></div><div><label className="text-sm text-slate-400">Punto de venta WSFE</label><input className={input} type="number" min="1" max="99999" value={form.pointOfSale} onChange={e=>setForm(f=>({...f,pointOfSale:Number(e.target.value)}))}/></div></div>
  <div className="grid sm:grid-cols-2 gap-3"><div><label className="text-sm text-slate-400">CUIT emisor</label><input className={input} value={form.cuit} onChange={e=>setForm(f=>({...f,cuit:e.target.value}))} placeholder="20XXXXXXXXX" required/></div><div><label className="text-sm text-slate-400">Razón social / nombre fiscal</label><input className={input} value={form.legalName} onChange={e=>setForm(f=>({...f,legalName:e.target.value}))}/></div></div>
  <div><label className="text-sm text-slate-400">Domicilio comercial</label><input className={input} value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))}/></div>
  <div className="grid sm:grid-cols-2 gap-3"><div><label className="text-sm text-slate-400">Ingresos Brutos</label><input className={input} value={form.grossIncomeNumber} onChange={e=>setForm(f=>({...f,grossIncomeNumber:e.target.value}))}/></div><div><label className="text-sm text-slate-400">Inicio de actividades</label><input className={input} type="date" value={form.activityStartDate} onChange={e=>setForm(f=>({...f,activityStartDate:e.target.value}))}/></div></div>
  <div className="grid sm:grid-cols-2 gap-3"><div><label className="text-sm text-slate-400">Certificado ARCA (.crt/.pem)</label><input className="block w-full text-sm text-slate-400 mt-1" type="file" accept=".crt,.pem,.cer" onChange={e=>readFile(e.target.files?.[0],'certificate')}/><p className={`text-xs mt-1 ${meta?.hasCertificate?'text-emerald-400':'text-amber-400'}`}>{meta?.hasCertificate?`Cargado${meta.certificateExpiresAt?' · vence '+new Date(meta.certificateExpiresAt).toLocaleDateString():''}`:'Sin certificado'}</p></div><div><label className="text-sm text-slate-400">Clave privada (.key/.pem)</label><input className="block w-full text-sm text-slate-400 mt-1" type="file" accept=".key,.pem" onChange={e=>readFile(e.target.files?.[0],'privateKey')}/><p className={`text-xs mt-1 ${meta?.hasPrivateKey?'text-emerald-400':'text-amber-400'}`}>{meta?.hasPrivateKey?'Cargada y protegida':'Sin clave privada'}</p></div></div>
  <p className="text-xs text-slate-500">Los archivos se cifran en la API y nunca vuelven a mostrarse ni se guardan en GitHub.</p>
  {message&&<p className={`text-sm ${message.includes('correct')||message.includes('guardada')?'text-emerald-400':'text-amber-300'}`}>{message}</p>}
  <div className="flex flex-wrap gap-2"><button disabled={saving} className="px-4 py-2 rounded-lg btn-brand disabled:opacity-50">{saving?'Guardando...':'Guardar ARCA'}</button><button type="button" disabled={testing||!meta?.hasCertificate||!meta?.hasPrivateKey} onClick={test} className="px-4 py-2 rounded-lg border border-cyan-700 text-cyan-200 hover:bg-cyan-950 disabled:opacity-40">{testing?'Probando comunicación...':'Probar comunicación'}</button></div>
 </form>;
}